// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package genframe

import (
	"go.genframe.xyz/config"
	"go.genframe.xyz/internal/genframe/controller/bluetooth"
	"go.genframe.xyz/internal/genframe/usecase"
	"go.genframe.xyz/pkg/chrome"
	"go.genframe.xyz/pkg/wifi"
)

// Injectors from wire.go:

func InitializeGenframe() *Genframe {
	configConfig := config.ProvideConfig()
	wifiWifi := wifi.ProvideWifi()
	chromeChrome := chrome.ProvideChrome()
	usecaseUsecase := usecase.ProvideUsecase(chromeChrome, configConfig, wifiWifi)
	bluetoothBluetooth := bluetooth.ProvideBluetooth(configConfig, usecaseUsecase, chromeChrome)
	genframe := ProvideGenframe(configConfig, wifiWifi, chromeChrome, usecaseUsecase, bluetoothBluetooth)
	return genframe
}
