// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"go.genframe.xyz/config"
)

// Injectors from wire.go:

func InitializeBootstrap() *Bootstrap {
	configConfig := config.ProvideConfig()
	bootstrap := ProvideBootstrap(configConfig)
	return bootstrap
}
